### ISSUE TITLE
Read Scratch doesn't seem to return anything

### ISSUE THREAD

**Issue by toofewacres** [PunchThrough/node-red-contrib-bean#11]
Installed Node Red on my PI2 just fine. Add bean nodes, All work except for the Read Scratch. I get read temp, accel, lcd, serial and write scratch to work (verified write by reading on the local bean and outputting as serial). But only get a "null" value returned on ReadScratch thru NodeRed. I have tried string, number, and buffer without getting any results. 

Is there something different about writing to the scratch locations so that they can be read thru Node-Red?

**Comment by swstack** [comment]
Hi @toofewacres ... there was a bug and it is fixed now. Please update your Bean Nodes to `v0.5.1` by running this command `npm update --prefix ~/.node-red node-red-contrib-bean`.

If this doesn't work please re-open the issue and I can assist you further.

Thanks!
